### ISSUE TITLE
Database schema

### ISSUE THREAD

**Issue by allyjweir** [allyjweir/aggressive-backpack#13]
This needs sorted. as pointed out by Leif at the presentation we hadn't thought through all the interactions. This is something worth actioning at this weeks lab (Tuesday 25th Feb)

**Comment by allyjweir** [comment]
The current views.py is completely wrong. It has a custom written user model instead of using Django's user authentication #5 . Has no one read the textbook? Chapter 8 people!

**Comment by ppyordanov** [comment]
I made a mistake. Will fix that and revise the book.

**Comment by allyjweir** [comment]
![1901224_10202594998929581_78848011_n](https://f.cloud.github.com/assets/3640069/2260298/0b8a0c86-9e40-11e3-9304-b68a71d1ba50.jpg)

**Comment by allyjweir** [comment]
Fields layout
- User - basics (given by django user) plus website, github, friends list(array)
- Project - id, name, desc, picture, milestones, tasks, who can edit?(only when logged in or anyone (public/private editing basically. a boolean))_anything else I've forgotten?_
- Task - id, name, text, assignees, tags (array of user-defined?), progress (int limited to 100 for user to set)
- Milestone - id, project(foreign key), name, due date, tasks, progress(calculated by number of tasks at 100%

Sound about right?

**Comment by ppyordanov** [comment]
The models I made can be modified if some things need to be changed:

https://github.com/Kaffse/dim3-teamt/blob/allyInterface/aggressiveBackpack/models.py

**Comment by allyjweir** [comment]
Projects should probably has followers as well.

**Comment by ppyordanov** [comment]
"User - basics (given by django user) plus website, github, friends list(array)"
We spoke about things being overcomplicated already so I think the basic Django authentication + avatar is enough and, Django field types do not have arrays (read: https://docs.djangoproject.com/en/dev/ref/models/fields/#field-types)

We will need another model for friends using a many-to-many relationship, I think at the moment we need to implement must have features and then concentrate on possible enhancements.

**Comment by ppyordanov** [comment]
I have added a friends class and tag class to be able store user friends and task tags if we decide to implement this (have enough time).

**Comment by leifos** [comment]
Agreed - use the Django User model and save yourselves a world of hurt.
