### ISSUE TITLE
collaborator block

### ISSUE THREAD

**Issue by allyjweir** [allyjweir/aggressive-backpack#26]
need to create a block that shows friends and their projects on the RHS of the dashboard. Project names should link to their projects if user is also a team member.

see prototype here https://docs.google.com/presentation/d/17wDcwCy9t_2nMox4KuVBKrv8DJ6ueVUaXi3OrerJYH4/edit#slide=id.g2a37f181b_046

The views and models support this already

**Comment by ppyordanov** [comment]
This is almost completed, friends need to be displayed

**Comment by ppyordanov** [comment]
Now completed.
