### ISSUE TITLE
Basic front end set up

### ISSUE THREAD

**Issue by ppyordanov** [allyjweir/aggressive-backpack#3]
We need to set up the web application and test the populated database.

**Comment by kaffo** [comment]
I believe I've done settings.py (except you guys need to add your names) and it should be ready to make a database locally and start making pages/coding.

**Comment by ppyordanov** [comment]
Oh sorry I modified your file because after posting the ticket I started working on it I will see what I can salvage.

PS: Actually I think your changes are there. You can check and see.

**Comment by ppyordanov** [comment]
Ok after setting up Django I created the webapp template. Decided to use the one I started making for the team project. There are still a lot of details and things to be improved but you can get an idea of how it is going to look. I have included header.php and footer.php but they have not been added to the files yet for easier display on the local server. I need to set up apache to work in the dim3 directory.

**Comment by ppyordanov** [comment]
PS forgot to mention that you could only see the complete template after running the server as I've used the Django format for linking files in in the static directory and referencing context variables in views.py.

**Comment by ppyordanov** [comment]
I intend to use this template extension structure to further develop the template and dynamically fill the pages with database information at a later stage

https://docs.djangoproject.com/en/dev/topics/templates/
