### ISSUE TITLE
User Authentication

### ISSUE THREAD

**Issue by ppyordanov** [allyjweir/aggressive-backpack#5]
We need to have user authentication on the website to store user's preferences and projects as well as collaborative information.

**Comment by kaffo** [comment]
User's need to be a thing, I'm sure it's part of the requirements being able to invite a set group of people to look at your lists.

**Comment by ppyordanov** [comment]
Yes I put it like this because we could also use an open id as an option, I mean you visit the site and choose a random anon/else id, but having user accounts is better indeed.

**Comment by kaffo** [comment]
It's fine. I'll do this and it'll be fine. Did I mention it'll be fine?

**Comment by allyjweir** [comment]
This is not a could, it is a must! How useful would a project manager be if another user could access and mess up your lists etc? We are using the default django user authentication. Chapter 8 in the textbook!

**Comment by allyjweir** [comment]
Done
