### ISSUE TITLE
Learn a little jQuery

### ISSUE THREAD

**Issue by allyjweir** [allyjweir/aggressive-backpack#8]
Here is a list of decent resources for anyone looking to brush up (or like me start learning at all) some jQuery.
- https://jqueryui.com/
- https://jqueryui.com/sortable/ _More a specific one but still useful_
- http://www.codecademy.com/tracks/jquery
- http://jqfundamentals.com/

**Comment by ppyordanov** [comment]
(y) Yup these are really good I used some of them to test how it works and just saw that the codeacadamy demos are even better will check them out ;)
